project_id = "dklhiwknxpodxfprwjhn"

[functions.scrape-site-branding]
verify_jwt = false

[functions.api-proxy]
verify_jwt = false

[functions.create-verification-session]
verify_jwt = false

[functions.get-verification-status]
verify_jwt = false

[functions.address-verification]
verify_jwt = false
